### ISSUE TITLE
PIP package for the new vesion

### ISSUE THREAD

**Issue by tvieira** [mkollaro/taskrunner#18]
The taskrunner package within PyPI servers is still the old version. Are you going to upload the new package? Thank you!

**Comment by ryankwilliams** [comment]
Hi, I am also looking for the latest version of taskrunner on PyPI servers. My project would benefit from PR #17. Will a new package be available?

Thank you!

**Comment by mkollaro** [comment]
Hi, thanks for the ping, I completely forgot about this. It should be out on PyPI now.

**Comment by ryankwilliams** [comment]
Just checked PyPI and the latest version is there. Thank you!
